language: node_js
node_js:
- '10'
before_script:
- npm i -g github-markdown
- npm run prebuild
script:
- npm run build
- rm -rf .git
- git init
- git config user.name "n3taway"
- git config user.email "n3taway@gmail.com"
- git add .
- git commit -m "update note"
- git push --force https://$TOKEN@github.com/n3tawayShadow/n3tawayShadow.github.io.git master
env:
  global:
    secure: pHhk8zu4jvWuQRs+inDy6V+ftz4yVT/SQZ0bypCT9ExwpBLJVaQTv5A5+NfyWFyMdrD+jRj11TU621qaSrPrkuudDBSBEkC7IR8uG+abTErRq+b9j6l0hx4+4J7wSWhlVkXjSqQf8N2k3/3HNJlWCVe8qmzZBTLRWhvKHdaaTcDBul0cc5kTyQvmC4sWGY09VeXqqMeDhjihdFAd+4No/FOt2NyP8TNO4iPt1YkmO6ClOc8jNrprT4TcNzCjZWbQhqX84XVI4tq4RFWALKnt10IYJU5m/776r/w+cFGuidPV8PPX6jDqHqlZaNuOwLUwmobf5mC5D3EJ34boS79kQUvn2Dd5t4D+WoYiHRts7xXnHEYWj2pnHly8e7c4nNIwNQcd/R+xTO5Rtvz5UUo06lMTxowr59wGz0SImiQ8cynBjntg1NHlYOCEFfrHJjOwlnreGgw9CyM+3Wk8L+xaqku4hTg26/HfyU7VbXaowPv5sJGyhBJSef4UMwPZUUgHQiP/Qsh6ucDFKYtYNzXEIV6GcR66VwQVUx9LZDoSGltq2s74fQS7+Tk5HEPxBGRexoctcpTOFCG54tQEP8l0kkF+dm0LV8Nd/vuSrSc4xdnltT8MmBcDotCb4yYT6MoD4MuXxNSk90mxt1n4uLl9WNXJPLAV4jtw85Sb6MeOY3s=
